---
# Debian tasks for ansible-couchbase-server
## Couchbase Server

- name: Download and install meta package from Couchbase (Debian)
  become: true
  apt:
    deb: "{{ couchbase_server_debian_package }}"
    state: present
  tags: installation

- name: Install enterprise package latest (Debian)
  become: true
  apt:
    name: couchbase-server
    state: present
    update_cache: yes
  when: couchbase_server_edition == "enterprise" and couchbase_server_debian_version == "latest"
  tags: installation

- name: Install enterprise package version (Debian)
  become: true
  apt:
    name: couchbase-server={{ couchbase_server_debian_version }}
    state: present
    update_cache: yes
  when: couchbase_server_edition == "enterprise" and couchbase_server_debian_version != "latest"
  tags: installation

- name: Install community package latest (Debian)
  become: true
  apt:
    name: couchbase-server-community
    state: present
    update_cache: yes
  when: couchbase_server_edition == "community" and couchbase_server_debian_version == "latest"
  tags: installation

- name: Install community package version (Debian)
  become: true
  apt:
    name: couchbase-server-community={{ couchbase_server_debian_version }}
    state: present
    update_cache: yes
  when: couchbase_server_edition == "community" and couchbase_server_debian_version != "latest"
  tags: installation

# Firewall (optional)
- name: Firewall limitations (Debian)
  include: Debian_firewall.yml
  when: couchbase_server_firewall == True
