---
# File: tasks/main.yml - Main tasks for ansible-couchbase-server

- name: Distribution specific variables
  include_vars: "../vars/{{ ansible_os_family }}.yml"

- name: Tuning variables
  include_vars: ../vars/tuning.yml

- name: Update user limits
  become: true
  copy:
    src: "etc_security_limits.d_couchbase-server.conf"
    dest: "/etc/security/limits.d/couchbase-server.conf"
    owner: root
    group: root
    mode: 0644

- name: Install profile.d script
  become: true
  template:
    src: "profile_couchbase-server.sh.j2"
    dest: "/etc/profile.d/couchbase-server.sh"

- name: Optimized settings for Couchbase Server data and index volumes
  become: true
  mount:
    name: "{{ couchbase_server_mountpoint }}"
    src: "{{ couchbase_server_partition }}"
    opts: "{{ couchbase_server_mount_options }}"
    fstype: "{{ couchbase_server_filesystem }}"
    state: mounted
  when: couchbase_server_tune_os

- name: Kernel settings dir
  become: True
  file:
    dest: "/etc/sysctl.d"
    state: "directory"

- name: Kernel settings config
  become: true
  template:
    src: "etc_sysctl.d_couchbase-server.conf.j2"
    dest: "/etc/sysctl.d/couchbase-server.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Update kernel settings

- name: Disable THP
  become: true
  copy:
    src: rc.local
    dest: "/etc/rc.local"
    owner: root
    group: root
    mode: 0644
  notify: Source local settings

# Debian/Ubuntu tasks
- name: Debian
  import_tasks: Debian.yml
  when: ansible_os_family  == "Debian"

# RedHat/Centos tasks
- name: RedHat
  import_tasks: RedHat.yml
  when: ansible_os_family  == "RedHat"

- name: Couchbase Server Service
  service:
    name: couchbase-server
    state: started