---
# File: tasks/RedHat.yml - RHEL tasks for ansible-couchbase-server

- name: Install Python3
  yum:
    name: python3
    state: present
  tags: installation

# Download and install SELinux Python module (required by Ansible)
- name: Download and install meta package from Couchbase (RedHat)
  become: true
  yum:
    name: "{{ couchbase_server_centos_package }}"
    state: present
  tags: installation

- name: Install enterprise package latest (RedHat)
  become: true
  yum:
    name: couchbase-server
    state: present
    update_cache: yes
  when: couchbase_server_edition == "enterprise" and couchbase_server_centos_version == "latest"
  tags: installation

- name: Install enterprise package version (RedHat)
  become: true
  yum:
    name: couchbase-server-{{ couchbase_server_centos_version }}
    state: present
    update_cache: yes
  when: couchbase_server_edition == "enterprise" and couchbase_server_centos_version != "latest"
  tags: installation

- name: Install community package latest (RedHat)
  become: true
  yum:
    name: couchbase-server-community
    state: present
    update_cache: yes
  when: couchbase_server_edition == "community" and couchbase_server_centos_version == "latest"
  tags: installation

- name: Install community package version (RedHat)
  become: true
  yum:
    name: couchbase-server-community-{{ couchbase_server_centos_version }}
    state: present
    update_cache: yes
  when: couchbase_server_edition == "community" and couchbase_server_centos_version != "latest"
  tags: installation

# Firewall (optional)
- name: Firewall limitations (RedHat)
  include: RedHat_firewall.yml
  when: couchbase_server_firewall == True

