---
# File: tasks/Ubuntu.yml - Ubuntu tasks for ansible-couchbase-server
## Couchbase Server

- name: Download and install meta package from Couchbase (Ubuntu)
  become: true
  apt:
    deb: "{{ couchbase_server_ubuntu_package }}"
    state: present
  tags: installation

- name: Install enterprise package latest (Ubuntu)
  become: true
  apt:
    name: couchbase-server
    state: present
    update_cache: yes
  when: couchbase_server_edition == "enterprise" and couchbase_server_ubuntu_version == "latest"
  tags: installation

- name: Install enterprise package version (Ubuntu)
  become: true
  apt:
    name: couchbase-server={{ couchbase_server_ubuntu_version }}
    state: present
    update_cache: yes
  when: couchbase_server_edition == "enterprise" and couchbase_server_ubuntu_version != "latest"
  tags: installation

- name: Install community package latest (Ubuntu)
  become: true
  apt:
    name: couchbase-server-community
    state: present
    update_cache: yes
  when: couchbase_server_edition == "community" and couchbase_server_ubuntu_version == "latest"
  tags: installation

- name: Install community package version (Ubuntu)
  become: true
  apt:
    name: couchbase-server-community={{ couchbase_server_ubuntu_version }}
    state: present
    update_cache: yes
  when: couchbase_server_edition == "community" and couchbase_server_ubuntu_version != "latest"
  tags: installation

# Firewall (optional)
- name: Firewall limitations (Ubuntu)
  include: Ubuntu_firewall.yml
  when: couchbase_server_firewall == True
