---
- name: Install Nginx (Debian)
  apt:
    name: nginx
  tags: installation

- name: Install Couchbase Sync Gateway (Debian)
  become: true
  apt:
    deb: "{{ couchbase_sync_gateway_debian_package }}"
    state: present
  tags: installation

#  # Firewall (optional)
#  - name: Firewall limitations (Debian)
#    include: Debian_firewall.yml
#    when: couchbase_server_firewall == True