---
- name: Distribution specific variables
  include_vars: "../vars/{{ ansible_os_family }}.yml"
# Install on CentOS/RHEL
# RedHat tasks
- name: RedHat
  import_tasks: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Debian/Ubuntu tasks
- name: Debian
  import_tasks: Debian.yml
  when: ansible_os_family  == "Debian"

- name: Ensure nginx sites-available path exists.
  file:
    path: "/etc/nginx/sites-available/"
    state: directory

- name: Ensure nginx sites-enabled path exists.
  file:
    path: "/etc/nginx/sites-enabled/"
    state: directory

- name: Copy Nginx Main Settings
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
  tags:
    - installation
    - configuration

- name: Copy Nginx Site Settings
  template:
    src: sync_gateway.nginx.j2
    dest: /etc/nginx/sites-available/sync_gateway
  notify: Restart Nginx
  tags:
    - installation
    - configuration

- name: Apply Nginx Settings
  file:
    src: /etc/nginx/sites-available/sync_gateway
    dest: /etc/nginx/sites-enabled/sync_gateway
    state: link
  notify: Restart Nginx
  tags:
    - installation
    - configuration

- name: Copy Sync Gateway Settings
  template:
    src: couchbase-sync-gateway-import.json.j2
    dest: "/home/sync_gateway/sync_gateway.json"
    owner: "sync_gateway"
    mode: "u=rw,g=,o="
  notify: Restart Gateway
  tags:
    - installation
    - configuration

- name: Ensure Sync Gateway Service is started
  service:
    name: sync_gateway
    state: started
    enabled: yes
  tags:
    - installation

- name: Ensure Nginx Service is started
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - installation