---

- name: SELinux Python Module
  yum: name=libselinux-python state=present
  tags: installation

- name: Install Nginx (RedHat)
  yum: name=nginx
  tags: installation

- name: Install Sync Gateway (RedHat)
  yum: name=/tmp/{{ couchbase_sync_gateway_package }} state=present
  tags: installation