---
- name: Install Python3
  yum:
    name: python3
    state: present
  tags: installation

- name: Install Nginx (RedHat)
  yum:
    name: nginx
    state: present
  tags: installation

- name: Install Couchbase Sync Gateway (RedHat)
  become: true
  yum:
    name: "{{ couchbase_sync_gateway_redhat_package }}"
    state: present
  tags: installation