---
# File: create_buckets.yml
# Example Ansible playbook to create a new Couchbase Server bucket
- hosts: primary
  become: false
  tasks:
    - name: Verify node health
      shell: "{{ couchbase_server_bin_path }}/couchbase-cli server-list -c {{ ansible_fqdn }}:{{ couchbase_server_admin_port }} -u {{ couchbase_server_admin }} -p {{ couchbase_server_password }} | awk '/:{{ couchbase_server_admin_port }}/ {print $3}'"
      register: couchbase_server_health
      failed_when: couchbase_server_health['stdout_lines'][0] != "healthy"
      changed_when: False

    - name: Create users
      shell: "{{ couchbase_server_bin_path }}/couchbase-cli user-manage -c {{ ansible_fqdn }}:{{ couchbase_server_admin_port }} -u {{ couchbase_server_admin }} -p {{ couchbase_server_password }} --set --rbac-username {{item.username}} --rbac-password {{item.password}} --roles {{ item.roles}} --auth-domain local"
      loop: "{{ users }}"