---
# File: retreive_ssl_cert.yml
# Ansible playbook to grab SSL certificates from all cluster nodes
# This playbook only works with Enterprise Edition
- hosts: primary
  gather_facts: False
  become: true

  tasks:
  - name: Remove previous local data
    become: false
    local_action: file name=var/ssl_certs/*.pem state=absent

  - name: Ensure local data dir exists
    become: false
    local_action: file name=var/ssl_certs state=directory

  - name: Store SSL certificate
    shell: "{{ couchbase_server_bin_path }}/couchbase-cli ssl-manage --cluster-cert-info -c {{ ansible_fqdn }}:{{ couchbase_server_admin_port }} -u {{ couchbase_server_admin }} -p {{ couchbase_server_password }} > /tmp/{{ ansible_fqdn }}.pem"

  - name: Fetch SSL certificate
    fetch:
      src:  /tmp/{{ ansible_fqdn }}.pem
      dest: ../{{ ansible_hostname }}.pem
      flat: true

  - name: Cleanup
    file:
      path: /tmp/{{ ansible_fqdn }}.pem
      state: absent
